import 'package:get/get.dart';

class LocaleString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        // ENGLISH LANGUAGE
        'en_US': {
          'hi': 'Hi',
          'take_glucose_reading': 'Take Glucose Reading',
          'screening_reports': 'Screening Reports',
          'how_to_use_app': 'How to use this application?',
          'edit_profile': 'Edit Profile',
          'write_review': 'Write a Review',
          'privacy_policy': 'Privacy Policy',
          'terms_of_use': 'Terms of Use',
          'faq': 'FAQ',
          'log_out': 'Log Out',
          'prick_finger': 'Prick your finger with lancet to get blood sample',
          'use_new_lancet': 'Always use a new lancet to test the sugar level.',
          'set_lancet_depth':
              'Depending on how deep the lancet goes into your skin, you can set it according to the rotator or in the lancet device.',
          'add_blood_sample': 'Add blood sample to test strip',
          'hold_drop_of_blood': 'Hold a drop of blood against the test strip\'s edge.',
          'touch_glucose_strip': 'Touch the glucose strip on the drop of blood.',
          'back': 'Back',
          'next': 'Next',
          'scan_test_strip_timer': 'Scan the test strip after timer ends',
          'wait_till_timer_end': 'Wait till timer end & scan the test strip',
          'get_glucose_readings': 'Get your glucose readings.',
          'home': 'Home',
          'cancel': 'Cancel',
          'save': 'Save',
          'name': 'Name',
          'age': 'Age',
          'state': 'State',
          'mobile_number': 'Mobile Number',
          'logout_confirmation': 'Are you sure you want to logout?',
          'scan_strip_timer_end': 'Scan the strip immediately after the timer ends.',
          'add_blood_video_next': 'Please add blood on the strip as shown in the video and then press Next.',
          'processing_message': ' processing...',
          'wait_1_minute': 'Please wait, approximately 1 minute.',
          'result': 'Result',
          'plasma_glucose_level': 'Plasma Glucose Level',
          'skip': 'Skip',
          'click_to_focus_strip': 'Click on screen to focus strip',
          'keep_mobile_still_during_countdown': 'Keep the mobile still for',
          'retake': 'Retake',
          'confirm_upload_video': 'Are you sure you want to upload the video?',
          'submit': 'Submit',
          'confirm_retake_video': 'Are you sure you want to Retake the video?',
          'yes': 'Yes',
          'no': 'No',
          'scan_again': 'Scan Again',
          'start_screening': 'Start Screening',
          'learn_more': 'Learn More',
          'date': 'Date',
          'prepap_value': 'Prepap Value',
          'support': 'Support',
          'email': 'Email',
          'phone': 'Phone',
          'enter_message': 'Enter your message',
          //Result Strings
          'what_it_means': 'What It Means:',
          'why_it_happens': 'Why It Happens:',
          'what_to_do': 'What to Do:',
          'mild_imbalance': 'MILD IMBALANCE',
          'vaginal_pH_info':
              'Sometimes, the pH level in your vagina can become a little too high (less acidic), upsetting the natural balance, similar to the water in your pond becoming less acidic.',
          'vaginal_pH_cause':
              'This can occur due to factors like using scented products or hormonal changes, disrupting the ecosystem\'s harmony.',
          'vaginal_pH_solution':
              'To restore the balance, you can avoid using strongly scented products and follow healthy habits. Sometimes, special products might help bring things back in order.',
          'moderate_imbalance': 'MODERATE IMBALANCE',
          'vaginal_pH_info_2':
              'Sometimes, the pH level in your vagina can become even more off-balance, like the water in your pond becoming less friendly for the good organisms.',
          'vaginal_pH_cause_2':
              'This could be due to neglecting proper care or a condition called "bacterial vaginosis," which disrupts the ecosystem with too much of certain bacteria.',
          'vaginal_pH_solution_2':
              'If you notice unusual smells, discomfort, or odd discharge, consider consulting a doctor. They can provide treatments that help restore the ecosystem\'s health.',
          'severe_imbalance': 'SEVERE IMBALANCE',
          'vaginal_pH_info_3':
              'Sometimes, the pH level can become significantly imbalanced, like the water in your pond becoming toxic for the helpful organisms.',
          'vaginal_pH_cause_3':
              'Serious issues like infections can cause this, such as infections you might get from unprotected sex, disturbing the ecosystem\'s harmony.',
          'vaginal_pH_solution_3':
              'If you experience intense itching, pain, or burning, it\'s crucial to seek medical attention. Doctors are like ecosystem experts who can diagnose and treat the problem to restore balance.',
          //Learn More
          'understanding_vaginal_ph': 'Understanding Vaginal pH',
          'unveiling_the_basics': 'Unveiling the Basics: What Is Vaginal pH and Why Does It Matter?',
          'the_science_behind_balance': 'The Science Behind Balance: How pH Affects Your Vaginal Health',
          'getting_to_know_your_body': 'Getting to Know Your Body: Exploring the Intricacies of Vaginal pH',
          'preventive_benefits_of_regular_screening': 'Preventive Benefits of Regular Screening',
          'navigating_a_ph_conscious_lifestyle': 'Navigating a pH-Conscious Lifestyle',
          'lets_begin': 'Let\'s Begin!',
          'your': 'Your',
          'journey': 'Journey.',
          'to_get_accurate_results': 'To get accurate results',
          'test_strip_should_be': 'Test strip should be ',
          'scanned_by_vertically_aligned_strip': 'scanned by keeping complete strip vertically aligned ',
          'in_the_bounding_box': 'in the bounding box ',
          'the_application': 'The application ',
          'should_accurately_display_mid_height_strip': 'should accurately display the strip at a mid-height position ',
          'and': 'and ',
          'background_should_be_white': 'background should be white ',
        },
        // HINDI LANGUAGE
        'hi_IN': {
          'background_should_be_white': 'पृष्ठभूमि सफेद होनी चाहिए। ',
          'and': 'और',
          'should_accurately_display_mid_height_strip':
              'मध्य ऊंचाई स्थिति पर स्ट्रिप को सटीकता से प्रदर्शित करना चाहिए ',

          'the_application': 'यह एप्लिकेशन ',
          'in_the_bounding_box': 'बाउंडिंग बॉक्स में ',
          'scanned_by_vertically_aligned_strip': 'पूर्ण स्ट्रिप को ऊर्ध्वाधिक रूप से एलाइन करके स्कैन किया गया ',
          'test_strip_should_be': 'टेस्ट स्ट्रिप होना चाहिए ',
          'to_get_accurate_results': 'सटीक परिणाम प्राप्त करने के लिए ',
          'journey': 'यात्रा',
          'your': 'आपका',
          'lets_begin': 'आइए शुरू करें!',
          'hi': 'नमस्ते',
          'take_glucose_reading': 'ग्लूकोज रीडिंग लें',
          'screening_reports': 'स्क्रीनिंग रिपोर्ट',
          'how_to_use_app': 'इस एप्लिकेशन का उपयोग कैसे करें?',
          'edit_profile': 'प्रोफ़ाइल संपादित करें',
          'write_review': 'समीक्षा लिखें',
          'privacy_policy': 'गोपनीयता नीति',
          'terms_of_use': 'उपयोग की शर्तें',
          'faq': 'पूछे जाने वाले प्रश्न',
          'log_out': 'लॉग आउट',
          'prick_finger': 'लैंसेट के साथ अपने उंगली को काटें और खून नमूना प्राप्त करें',
          'use_new_lancet': 'चीनी के स्तर का परीक्षण करने के लिए हमेशा एक नया लैंसेट का उपयोग करें।',
          'set_lancet_depth':
              'आपके त्वचा में लैंसेट कितने गहरे जाता है, आप इसे रोटेटर के अनुसार सेट कर सकते हैं या लैंसेट डिवाइस में।',
          'add_blood_sample': 'परीक्षण स्ट्रिप पर खून नमूना डालें',
          'hold_drop_of_blood': 'परीक्षण स्ट्रिप के किनारे पर एक बूंद खून पकड़ें।',
          'touch_glucose_strip': 'बूंद खून पर परीक्षण स्ट्रिप को छूंएं।',
          'back': 'पीछे',
          'next': 'अगला',
          'scan_test_strip_timer': 'टाइमर समाप्त होने के बाद परीक्षण स्ट्रिप स्कैन करें',
          'wait_till_timer_end': 'टाइमर समाप्त होने तक प्रतीक्षा करें और परीक्षण स्ट्रिप स्कैन करें',
          'get_glucose_readings': 'अपने ग्लूकोज रीडिंग प्राप्त करें।',
          'home': 'होम',
          'cancel': 'रद्द करें',
          'save': 'सहेजें',
          'name': 'नाम',
          'age': 'उम्र',
          'state': 'राज्य',
          'mobile_number': 'मोबाइल नंबर',
          'logout_confirmation': 'क्या आप वाकई लॉगआउट करना चाहते हैं?',
          'scan_strip_timer_end': 'टाइमर समाप्त होने के बाद स्ट्रिप को तुरंत स्कैन करें।',
          'add_blood_video_next': 'कृपया वीडियो में दिखाए गए तरीके से स्ट्रिप पर खून डालें और फिर अगला दबाएं।',
          'processing_message': 'हम प्रोसेस कर रहे हैं...',
          'wait_1_minute': 'कृपया प्रतीक्षा करें, लगभग 1 मिनट।',
          'result': 'परिणाम',
          'plasma_glucose_level': 'प्लाज्मा ग्लूकोज स्तर',
          'skip': 'छोड़ें',
          'click_to_focus_strip': 'स्ट्रिप पर फ़ोकस करने के लिए स्क्रीन पर क्लिक करें',
          'keep_mobile_still_during_countdown': 'कृपया गिनती के दौरान मोबाइल को ठिकाने दें',
          'retake': 'पुनः ले',
          'confirm_upload_video': 'क्या आप वीडियो अपलोड करना चाहते हैं?',
          'submit': 'प्रस्तुत करें',
          'confirm_retake_video': 'क्या आप वीडियो को पुनः लेना चाहते हैं?',
          'yes': 'हाँ',
          'no': 'नहीं',
          'scan_again': 'फिर से स्कैन करें',
          'start_screening': 'स्क्रीनिंग शुरू करें',
          'learn_more': 'और जानें',
          'date': 'तारीख',
          'prepap_value': 'प्रीपैप मूल्य',
          'support': 'समर्थन',
          'email': 'ईमेल',
          'phone': 'फ़ोन',
          'enter_message': 'अपना संदेश दर्ज करें',
          //Result String
          'what_it_means': 'इसका मतलब है:',
          'why_it_happens': 'यह क्यों होता है:',
          'what_to_do': 'क्या करें:',
          'mild_imbalance': 'हलका असंतुलन',
          'vaginal_pH_info':
              'कभी-कभी, आपकी योनि में pH स्तर थोड़ा ज्यादा उच्च (कम acidic), प्राकृतिक संतुलन को बिगाड़ सकता है, ठीक वैसे ही जैसे कुएं के पानी में अम्लीयता कम होने की तरह।',
          'vaginal_pH_cause':
              'इसका कारण सुगंधित उत्पादों का उपयोग करने या हार्मोनल परिवर्तन जैसे कारकों से हो सकता है, जो पारिस्थितिकी के संतुलन को बिगाड़ सकते हैं।',
          'vaginal_pH_solution':
              'संतुलन को पुनर्स्थापित करने के लिए, आपको तेजी से खुशबूदार उत्पादों का उपयोग कम करने के लिए और स्वस्थ आदतों का पालन करने की सलाह दी जा सकती है। कभी-कभी, विशेष उत्पाद बदलाव में मदद कर सकते हैं।',
          'moderate_imbalance': 'मध्यम असंतुलन',
          'vaginal_pH_info_2':
              'कभी-कभी, आपकी योनि में pH स्तर बिगड़ सकता है, ठीक वैसे ही जैसे कुएं के पानी में अच्छे जीवों की कमी होने की तरह।',
          'vaginal_pH_cause_2':
              'इसका कारण सही देखभाल की लापरवाही करने या "बैक्टीरियल वैजिनोसिस" नामक एक स्थिति के कारण हो सकता है, जिससे यहां विशिष्ट बैक्टीरिया का अधिक हो सकता है।',
          'vaginal_pH_solution_2':
              'यदि आप असामान्य गंध, असहजता या विचित्र विवरण दिखाते हैं, तो कृपया एक डॉक्टर से परामर्श करें। उन्हें ऐसे उपचार प्रदान किए जा सकते हैं जो पारिस्थितिकी की स्वास्थ्य को पुनर्स्थापित करने में मदद कर सकते हैं।',
          'severe_imbalance': 'गंभीर असंतुलन',
          'vaginal_pH_info_3':
              'कभी-कभी, pH स्तर महत्वपूर्ण रूप से असंतुलित हो सकता है, यथा आपके कुएं के पानी में सहायक जीवों के लिए विषाक्त होने की तरह।',
          'vaginal_pH_cause_3':
              'असुरक्षित संभोग से होने वाली संक्रमण जैसे गंभीर समस्याएं इसे उत्पन्न कर सकती हैं, जैसे कि आप अनप्रोटेक्टेड सेक्स से प्राप्त कर सकते हैं, जो पारिस्थितिकी के समंवय को बिगाड़ सकता है।',
          'vaginal_pH_solution_3':
              'अगर आपको तीव्र खुजली, दर्द या जलन महसूस होती है, तो डॉक्टर की सलाह लेना बहुत महत्वपूर्ण है। डॉक्टर ऐसे पारिस्थितिकी विशेषज्ञ होते हैं जो समस्या का निदान कर सकते हैं और संतुलन को पुनर्स्थापित करने के लिए उपचार कर सकते हैं।',
          //Learn More
          'understanding_vaginal_ph': 'योनि का pH समझना',
          'unveiling_the_basics': 'मूलभूत बातें प्रकट करना: योनि का pH क्या है और यह मायने रखता है?',
          'the_science_behind_balance': 'संतुलन के पीछे का विज्ञान: pH कैसे आपके योनि स्वास्थ्य को प्रभावित करता है',
          'getting_to_know_your_body': 'अपने शरीर को जानना: योनि के pH की जटिलताओं की खोज करना',
          'preventive_benefits_of_regular_screening': 'नियमित स्क्रीनिंग के रोकथामी लाभ',
          'navigating_a_ph_conscious_lifestyle': 'pH-सचेत जीवनशैली में नेविगेट करना',
        },
      };
}
